MOVE, EMPTY, WHITE, BLACK, TIE = 'Move', '.', 'O', 'X', 'Tie'
FIRST = WHITE
NORTH, NORTHEAST, NORTHWEST = [0, 1], [1, 1], [-1, 1]
SOUTH, SOUTHEAST, SOUTHWEST = [0, -1], [1, -1], [-1, -1]
EAST, WEST = [1, 0], [-1, 0]

DIRECTIONS = (NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST,
              NORTHWEST)

IMG_SIZE = 60
